#!/bin/bash
source .env

# Get current date in YYYY-MM-DD format
DATE=$(date +%Y-%m-%d)

# Set backup directory and filename
BACKUP_DIR="storage"
BACKUP_FILE="osticket_backup_${DATE}.sql"

# Create backup directory if it doesn't exist
mkdir -p $BACKUP_DIR

# Export database
mysqldump -h 127.0.0.1 -P 3306 -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" > "$BACKUP_DIR/$BACKUP_FILE"

# Check if backup was successful
if [ $? -eq 0 ]; then
    echo "Database backup completed successfully: $BACKUP_DIR/$BACKUP_FILE"
    # Compress the backup file
    cd $BACKUP_DIR
    zip "$BACKUP_FILE.zip" "$BACKUP_FILE"
    
    # Remove the uncompressed backup file
    wait 
    rm "$BACKUP_FILE"
else
    echo "Error: Database backup failed"
    exit 1
fi

